name: Deploy Backend

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to remote server
        run: sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh root@${{ secrets.SERVER_HOST }} 'bash -s' < deploy.sh
