name: Deploy Backend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t backend .

    - name: Tag Docker image
      run: docker tag backend:latest username/backend:latest

    - name: Push Docker image to Docker Hub
      run: docker push username/backend:latest

    - name: SSH into remote server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull username/backend:latest
          docker stop backend || true
          docker rm backend || true
          docker run -d --name backend -p 8080:8080 username/backend:latest 
